services:
  search:
    restart: unless-stopped

  app:
    environment:
      DB_HOST: ${DB_HOST:-175.0.105.249}
    restart: unless-stopped

  valhalla:
    restart: unless-stopped

  overpass:
    restart: unless-stopped
