import {
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  normalizeAgentTurnPayload,
  sortAgentSessions,
} from './normalizers.js'
import { createAgentSessionStoreMethods } from './session-store.js'
import { createAgentRuntimeMethods } from './runtime.js'
import { createAgentUiMethods } from './sessions-ui.js'
import { createAgentExecutionProfileMethods } from './execution-profile.js'
import { withAnalysisWorkspaceTabs } from './analysis-workspace-tabs.js'
export {
  buildAnalysisTaskParamBundle,
  buildAnalysisTaskParamBundles,
} from './analysis-task-params.js'

export {
  buildAnalysisTaskConfirmation,
  focusAnalysisTaskPanel,
  getAnalysisTaskDefinition,
  getAnalysisTaskDefinitions,
  resolveAnalysisTaskKeyFromTrace,
  runAnalysisTask,
} from './analysis-task-registry.js'

function createAnalysisAgentInitialState() {
  return {
    agentWorkspaceView: 'report',
    agentInput: '',
    agentLoading: false,
    agentStatus: 'idle',
    agentStage: 'gating',
    agentAnswer: '',
    agentExecutionTrace: [],
    agentUsedTools: [],
    agentCitations: [],
    agentResearchNotes: [],
    agentAuditIssues: [],
    agentPanelPayloads: {},
    agentClarificationQuestion: '',
    agentClarificationOptions: [],
    agentClarificationDraft: '',
    agentClarificationSubmitting: false,
    agentRiskPrompt: '',
    agentPendingTaskConfirmation: null,
    agentError: '',
    agentContextSummary: {},
    agentPlan: { steps: [], summary: '' },
    agentPlanExpanded: false,
    agentActiveExecutionProfile: {},
    agentTraceExpanded: false,
    agentPanelPreloadNotes: [],
    agentPreloadedPanelKeys: [],
    agentRiskConfirmations: [],
    agentMessages: [],
    agentComposerMenuOpen: false,
    agentComposerMode: '',
    agentCapabilitiesLoaded: false, agentCapabilitiesLoading: false, agentCapabilitiesError: '',
    agentModels: [], agentSkills: [], agentSelectedModelProfileId: '',
    agentSelectedSkillId: '', agentPinnedSkillId: '', agentSkillScope: 'turn',
    agentModelMenuOpen: false, agentModelConfigOpen: false, agentModelConfigMessage: '',
    agentModelForm: {},
    contextAskVisible: false,
    contextAskMinimized: false,
    contextAskLoading: false,
    contextAskError: '',
    contextAskDraft: '',
    contextAskSize: { width: 420, height: 560 },
    contextAskTarget: { type: '', id: '', title: '', source: '', summary: '', evidence: [], artifact_refs: [], payload: {} },
    contextAskMessages: [],
    agentThinkingTimeline: [],
    agentReasoningBlocks: [],
    agentStreamingMessageId: '',
    agentStreamState: 'idle',
    agentStreamStartedAt: 0,
    agentStreamElapsedTick: 0,
    agentStreamElapsedTimer: null,
    agentProgrammaticScrollUntil: 0,
    agentThinkingExpanded: false,
    agentMessageProcessExpandedIds: {},
    agentSessions: [],
    activeAgentSessionId: '',
    agentSessionsLoaded: false,
    agentSessionsLoading: false,
    agentSessionHydrating: false,
    agentSessionDetailLoadingId: '',
    agentSessionDetailRequestToken: 0,
    agentHistoryCollapsedGroups: {},
    agentTurnAbortController: null,
    agentRunRegistry: {},
    agentVisualSnapshotCache: {},
    agentSessionMenuId: '',
    agentRenameDialogOpen: false,
    agentRenameSessionId: '',
    agentRenameInput: '',
    agentTools: [],
    agentToolsLoaded: false,
    agentToolsLoading: false,
    agentToolsError: '',
    analysisCapabilities: [],
    analysisCapabilitiesLoaded: false,
    analysisCapabilitiesLoading: false,
    analysisCapabilitiesError: '',
    analysisCapabilityReadiness: {},
    analysisCapabilityReadinessErrors: {},
    analysisCapabilityReadinessLoading: false,
    activeAnalysisCapabilityId: '',
    analysisCapabilityRuns: [],
    analysisCapabilityRunsLoaded: false,
    analysisCapabilityRunsLoading: false,
    analysisCapabilityRunsError: '',
    analysisCapabilityRunsHistoryId: '',
    analysisCapabilityRunsCapabilityId: '',
    analysisCapabilityRunsRequestToken: 0,
    selectedAnalysisCapabilityRunId: '',
    selectedAnalysisCapabilityRunDetail: null,
    selectedAnalysisCapabilityRunLoading: false,
    selectedAnalysisCapabilityRunError: '',
    selectedAnalysisCapabilityRunRequestToken: 0,
    agentToolsViewMode: 'tools',
    agentToolDetailDialogOpen: false,
    agentActiveToolDetailName: '',
    basisDrawerOpen: false,
    basisDrawerPayload: null,
    basisDrawerActiveTab: 'basic',
    basisPromptEditMode: false,
    basisPromptDraft: { system_prompt: '', payload_note: '', output_schema_text: '' },
    basisPromptSaving: false,
    basisPromptError: '',
    basisPromptNotice: '',
    agentPromptConfigs: {},
    agentPptPlanningAutoPackageKeys: {},
    agentPptPlanningPackageErrors: {},
    agentPptPlanningWebSourceGenerating: false,
    agentPptPlanningSourceDeleting: false,
    agentAnalysisQuickAskAbortController: null,
    agentAnalysisQuickAskRequestId: 0,
    agentAnalysisQuickAskPendingId: '',
    agentTabs: withAnalysisWorkspaceTabs({
      summaryTabs: [],
      iterationChangeTabs: [],
      siteSelectionTabs: [],
      followupTabs: [],
      activeTabId: '',
      followupLimit: 6,
      nextFollowupNumber: 1,
    }, []),
    agentIterationActiveKind: 'poi',
    agentIterationSecondaryView: {
      poi: 'ai',
      population: 'metrics',
      nightlight: 'snapshots',
    },
    agentIterationPoiLoading: false,
    agentIterationPoiError: '',
    agentIterationPoiSnapshotCache: {},
    agentIterationPoiSnapshotGeneratingKey: '',
    agentIterationPoiAreaHeatmapCalibrationCache: {},
    agentIterationPoiAreaHeatmapCalibrationGeneratingKey: '',
    agentIterationPoiAreaHeatmapLayers: {
      mode: 'points',
      cells: false,
      points: true,
    },
    agentIterationPoiStructureSpatialView: {
      category: '',
      sortBy: 'count',
      spatialOnly: false,
    },
    agentIterationPopulationLoading: false,
    agentIterationPopulationError: '',
    agentIterationNightlightLoading: false,
    agentIterationNightlightError: '',
    agentIterationSnapshotDetailOpen: false,
    agentIterationSnapshotDetail: null,
    agentIterationSnapshotCopyStatus: '',
    agentIterationSnapshotCopyKey: '',
    agentSummaryReadiness: {
      checked: false,
      ready: false,
      missingTasks: [],
      reused: [],
      fetched: [],
    },
    agentSummaryLoading: false,
    agentSummaryGenerating: false,
    agentSummaryProgressPhase: '',
    agentSummaryStreamSections: {},
    agentSummaryError: '',
    agentSummaryWarnings: [],
    summaryTaskBoard: {
      runState: 'idle',
      tasks: [],
      lastRunAt: '',
    },
    summaryTaskLogTrackers: {},
  }
}

function createAnalysisAgentSessionMethods() {
  return {
    ...createAgentSessionStoreMethods(),
    ...createAgentRuntimeMethods(),
    ...createAgentUiMethods(),
    ...createAgentExecutionProfileMethods(),
  }
}

export {
  createAnalysisAgentInitialState,
  createAnalysisAgentSessionMethods,
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentTurnPayload,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  sortAgentSessions,
}
