import {
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  normalizeAgentTurnPayload,
  sortAgentSessions,
} from './normalizers.js'
import { createAgentSessionStoreMethods } from './session-store.js'
import { createAgentRuntimeMethods } from './runtime.js'
import { createAgentUiMethods } from './sessions-ui.js'
export {
  buildAnalysisTaskParamBundle,
  buildAnalysisTaskParamBundles,
} from './analysis-task-params.js'

export {
  buildAnalysisTaskConfirmation,
  focusAnalysisTaskPanel,
  getAnalysisTaskDefinition,
  getAnalysisTaskDefinitions,
  resolveAnalysisTaskKeyFromTrace,
  runAnalysisTask,
} from './analysis-task-registry.js'

function createAnalysisAgentInitialState() {
  return {
    agentWorkspaceView: 'report',
    agentInput: '',
    agentLoading: false,
    agentStatus: 'idle',
    agentStage: 'gating',
    agentAnswer: '',
    agentExecutionTrace: [],
    agentUsedTools: [],
    agentCitations: [],
    agentResearchNotes: [],
    agentAuditIssues: [],
    agentPanelPayloads: {},
    agentClarificationQuestion: '',
    agentClarificationOptions: [],
    agentClarificationDraft: '',
    agentClarificationSubmitting: false,
    agentRiskPrompt: '',
    agentPendingTaskConfirmation: null,
    agentError: '',
    agentContextSummary: {},
    agentPlan: { steps: [], followupSteps: [], followupApplied: false, summary: '' },
    agentPlanExpanded: false,
    agentTraceExpanded: false,
    agentPanelPreloadNotes: [],
    agentPreloadedPanelKeys: [],
    agentRiskConfirmations: [],
    agentAttachments: [],
    agentAttachmentIds: [],
    agentAttachmentUploading: false,
    agentAttachmentError: '',
    agentAttachmentPollTimer: null,
    agentMessages: [],
    agentDeepAnalysisMode: 'quick',
    agentComposerMenuOpen: false,
    agentComposerMode: '',
    contextAskVisible: false,
    contextAskMinimized: false,
    contextAskLoading: false,
    contextAskError: '',
    contextAskDraft: '',
    contextAskSize: { width: 420, height: 560 },
    contextAskTarget: { type: '', id: '', title: '', source: '', summary: '', evidence: [], artifactRefs: [], payload: {} },
    contextAskMessages: [],
    agentThinkingTimeline: [],
    agentReasoningBlocks: [],
    agentStreamingMessageId: '',
    agentStreamState: 'idle',
    agentStreamStartedAt: 0,
    agentStreamElapsedTick: 0,
    agentStreamElapsedTimer: null,
    agentProgrammaticScrollUntil: 0,
    agentThinkingExpanded: false,
    agentMessageProcessExpandedIds: {},
    agentSessions: [],
    activeAgentSessionId: '',
    agentSessionsLoaded: false,
    agentSessionsLoading: false,
    agentSessionHydrating: false,
    agentSessionDetailLoadingId: '',
    agentSessionDetailRequestToken: 0,
    agentHistoryCollapsedGroups: {},
    agentTurnAbortController: null,
    agentRunRegistry: {},
    agentSessionMenuId: '',
    agentRenameDialogOpen: false,
    agentRenameSessionId: '',
    agentRenameInput: '',
    agentTools: [],
    agentToolsLoaded: false,
    agentToolsLoading: false,
    agentToolsError: '',
    agentToolsViewMode: 'tools',
    agentToolDetailDialogOpen: false,
    agentActiveToolDetailName: '',
    basisDrawerOpen: false,
    basisDrawerPayload: null,
    basisDrawerActiveTab: 'basic',
    basisPromptEditMode: false,
    basisPromptDraft: { system_prompt: '', payload_note: '', output_schema_text: '' },
    basisPromptSaving: false,
    basisPromptError: '',
    basisPromptNotice: '',
    agentPromptConfigs: {},
    agentTabs: {
      summaryTab: {
        id: 'summary',
        frozen: true,
        createdAt: '',
        content: {},
        evidenceRefs: [],
      },
      summaryTabs: [],
      iterationChangeTabs: [],
      siteSelectionTabs: [],
      deepAnalysisTabs: [],
      followupTabs: [],
      activeTabId: '',
      followupLimit: 6,
      nextFollowupNumber: 1,
    },
    agentIterationActiveKind: 'poi',
    agentIterationSecondaryView: {
      poi: 'ai',
      population: 'metrics',
      nightlight: 'snapshots',
    },
    agentIterationPoiLoading: false,
    agentIterationPoiError: '',
    agentIterationPoiSnapshotCache: {},
    agentIterationPoiSnapshotGeneratingKey: '',
    agentIterationPoiAreaHeatmapCalibrationCache: {},
    agentIterationPoiAreaHeatmapCalibrationGeneratingKey: '',
    agentIterationPoiAreaHeatmapLayers: {
      mode: 'points',
      cells: false,
      points: true,
    },
    agentIterationPoiStructureSpatialView: {
      category: '',
      sortBy: 'count',
      spatialOnly: false,
    },
    agentIterationPopulationLoading: false,
    agentIterationPopulationError: '',
    agentIterationNightlightLoading: false,
    agentIterationNightlightError: '',
    agentIterationSnapshotDetailOpen: false,
    agentIterationSnapshotDetail: null,
    agentIterationSnapshotCopyStatus: '',
    agentIterationSnapshotCopyKey: '',
    agentSummaryReadiness: {
      checked: false,
      ready: false,
      missingTasks: [],
      reused: [],
      fetched: [],
    },
    agentSummaryLoading: false,
    agentSummaryGenerating: false,
    agentSummaryProgressPhase: '',
    agentSummaryStreamSections: {},
    agentSummaryError: '',
    agentSummaryWarnings: [],
    summaryTaskBoard: {
      runState: 'idle',
      tasks: [],
      lastRunAt: '',
    },
    summaryTaskLogTrackers: {},
  }
}

function createAnalysisAgentSessionMethods() {
  return {
    ...createAgentSessionStoreMethods(),
    ...createAgentRuntimeMethods(),
    ...createAgentUiMethods(),
  }
}

export {
  createAnalysisAgentInitialState,
  createAnalysisAgentSessionMethods,
  deriveAgentSessionPreview,
  deriveAgentSessionTitle,
  normalizeAgentTurnPayload,
  normalizeAgentSessionSummary,
  normalizeAgentToolSummary,
  sortAgentSessions,
}
