from __future__ import annotations

from typing import Dict

from .common import RegisteredTool, _register, _tool_spec
from ..tool_adapters.analysis_tools import (
    analyze_poi_mix_from_scope,
    analyze_target_supply_gap_from_scope,
    detect_commercial_hotspots_from_scope,
    read_h3_structure_analysis,
    read_nightlight_pattern_analysis,
    read_poi_structure_analysis,
    read_population_profile_analysis,
    read_road_pattern_analysis,
)
from ..tool_adapters.business_tools import run_business_site_advice


def register_analysis_business_tools(registry: Dict[str, RegisteredTool]) -> None:
    registry["read_poi_structure_analysis"] = _register(
        _tool_spec(
            name="read_poi_structure_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的 POI 业态结构分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="poi",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_poi_structure_analysis"],
            applicable_scenarios=["业态结构复核", "POI 结构复用"],
            produces=["current_poi_structure_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "dominant_categories": {"type": "array"},
                    "dining_ratio": {"type": "number"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_poi_structure_analysis,
    )
    registry["read_h3_structure_analysis"] = _register(
        _tool_spec(
            name="read_h3_structure_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的 H3 结构化分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="grid",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_h3_structure_analysis"],
            applicable_scenarios=["空间网格结构复核", "H3 结构复用"],
            produces=["current_h3_structure_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "distribution_pattern": {"type": "string"},
                    "structure_signal_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_h3_structure_analysis,
    )
    registry["read_road_pattern_analysis"] = _register(
        _tool_spec(
            name="read_road_pattern_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的路网结构模式分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="road",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_road_pattern_analysis"],
            applicable_scenarios=["路网结构复核", "可达性模式复用"],
            produces=["current_road_pattern_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "metric": {"type": "string"},
                    "node_count": {"type": "integer"},
                    "edge_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_road_pattern_analysis,
    )
    registry["read_population_profile_analysis"] = _register(
        _tool_spec(
            name="read_population_profile_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的人口结构画像，包含每个年龄段占比、主导年龄段、主导年龄段占比和主导年龄格子占比",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="population",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_population_profile_analysis"],
            applicable_scenarios=["人口承载复核", "人口画像复用"],
            produces=["current_population_profile_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "view": {"type": "string"},
                    "total_population": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "top_age_band": {"type": "string"},
                    "top_age_band_population": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "top_age_band_ratio": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "age_distribution_ratios": {"type": "array"},
                    "dominant_cell_ratio": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_population_profile_analysis,
    )
    registry["read_nightlight_pattern_analysis"] = _register(
        _tool_spec(
            name="read_nightlight_pattern_analysis",
            description="读取当前 snapshot 与 frontend_analysis 中的夜光活力结构分析",
            category="information",
            layer="L1",
            ui_tier="capability",
            data_domain="nightlight",
            capability_type="analyze",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_nightlight_pattern_analysis"],
            applicable_scenarios=["夜间活力复核", "夜光结构复用"],
            produces=["current_nightlight_pattern_analysis"],
            input_schema={"type": "object", "properties": {}, "additionalProperties": False},
            output_schema={
                "type": "object",
                "properties": {
                    "data_status": {"type": "string", "enum": ["ready", "empty"]},
                    "evidence_ready": {"type": "boolean"},
                    "view": {"type": "string"},
                    "total_radiance": {"anyOf": [{"type": "number"}, {"type": "null"}]},
                    "core_hotspot_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
        ),
        read_nightlight_pattern_analysis,
    )
    registry["analyze_poi_mix_from_scope"] = _register(
        _tool_spec(
            name="analyze_poi_mix_from_scope",
            description="基于当前 POI 结构结果生成商业画像和功能复合判断",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="poi",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="area_character",
            toolkit_id="area_character_pack",
            evidence_contract=["current_business_profile", "current_poi_structure_analysis"],
            applicable_scenarios=["商业画像解释", "功能复合判断"],
            produces=["current_business_profile", "current_poi_structure_analysis"],
            readonly=True,
            cost_level="normal",
        ),
        analyze_poi_mix_from_scope,
    )
    registry["detect_commercial_hotspots"] = _register(
        _tool_spec(
            name="detect_commercial_hotspots",
            description="基于 H3 结构结果识别商业核心区、次核心区与机会区",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="grid",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            evidence_contract=["current_commercial_hotspots", "current_h3_structure_analysis"],
            applicable_scenarios=["热点识别", "商业核心区识别"],
            produces=["current_commercial_hotspots", "current_h3_structure_analysis", "current_poi_structure_analysis"],
            input_schema={
                "type": "object",
                "properties": {
                    "target_category": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "hotspot_mode": {"type": "string"},
                    "core_zone_count": {"type": "integer"},
                    "opportunity_zone_count": {"type": "integer"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
            cost_level="normal",
        ),
        detect_commercial_hotspots_from_scope,
    )
    registry["analyze_target_supply_gap"] = _register(
        _tool_spec(
            name="analyze_target_supply_gap",
            description="基于当前 H3 结构结果判断目标业态供给缺口等级与空间错配",
            category="processing",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="interpret",
            llm_exposure="secondary",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            evidence_contract=["current_target_supply_gap"],
            applicable_scenarios=["目标业态缺口判断", "空间供需错配识别"],
            cautions=["缺少 H3 gap 结果时只能给弱判断"],
            produces=["current_target_supply_gap", "current_h3_structure_analysis"],
            input_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                },
                "required": ["place_type"],
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "supply_gap_level": {"type": "string"},
                    "gap_mode": {"type": "string"},
                    "summary_text": {"type": "string"},
                },
                "additionalProperties": True,
            },
            readonly=True,
            cost_level="normal",
        ),
        analyze_target_supply_gap_from_scope,
    )
    registry["run_business_site_advice"] = _register(
        _tool_spec(
            name="run_business_site_advice",
            description="生成开店/选址建议组合分析，串联 POI/H3/人口/夜光/路网证据",
            category="action",
            layer="L2",
            ui_tier="capability",
            data_domain="commerce",
            capability_type="decide",
            llm_exposure="hidden",
            scene_type="site_selection",
            toolkit_id="site_selection_pack",
            default_policy_key="business_catchment_1km",
            evidence_contract=["business_site_advice", "current_poi_h3_summary", "current_population_summary", "current_nightlight_summary", "current_road_summary"],
            applicable_scenarios=["开店选址建议", "多源商业证据串联"],
            cautions=["优先使用更细粒度证据工具完成可解释诊断；该工具适合需要一次性组合建议时使用"],
            requires=["scope_polygon"],
            produces=[
                "business_site_advice",
                "current_pois",
                "current_poi_summary",
                "current_poi_h3",
                "current_poi_h3_grid",
                "current_poi_h3_summary",
                "current_poi_h3_charts",
                "current_population",
                "current_population_summary",
                "current_nightlight",
                "current_nightlight_summary",
                "current_road",
                "current_road_summary",
            ],
            input_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "source": {"type": "string", "enum": ["local", "gaode"]},
                    "year": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "max_count": {"type": "integer", "minimum": 1, "maximum": 5000},
                    "resolution": {"type": "integer", "minimum": 0},
                    "include_mode": {"type": "string"},
                    "min_overlap_ratio": {"type": "number", "minimum": 0},
                    "neighbor_ring": {"type": "integer", "minimum": 0},
                    "mode": {"type": "string"},
                    "graph_model": {"type": "string"},
                    "highway_filter": {"type": "string"},
                },
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "place_type": {"type": "string"},
                    "types": {"type": "string"},
                    "keywords": {"type": "string"},
                    "poi_count": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                    "h3_grid_count": {"anyOf": [{"type": "integer"}, {"type": "null"}]},
                },
                "required": ["place_type", "types", "keywords"],
                "additionalProperties": True,
            },
            cost_level="expensive",
            timeout_sec=900,
        ),
        run_business_site_advice,
    )

